### PR TITLE
Allow per-usergroup configuration of points-per-minute

### PR DESCRIPTION
**Pull request by PatPeter**
This pull request will allow users to customize how many points they want each user group to receive and at what intervals.

### CODE REVIEW

**Comment by MrUnknownGamer** [comment]
This is very nice and I am hoping someone will try to work on this again though I would like it to just be the default message like "You have been given {points} for playing on the server" I would not like it to define "for {time} minutes. 

This would be a good idea for donors and would encourage them to donate again.

**Comment by PatPeter** [comment]
Just closing my pull request without even replying to my last comment? Sounds like someone was bested.

**Comment by HandsomeMatt** [comment]
Uh. Fuck off - poorly coded, useless feature. Best my dick in your ass, ya' smelly cunt.

**Comment by PatPeter** [comment]
MrUnknownGamer agreed with me that this is a good feature (especially for donors), and you failed to provide burden of proof that this is a poorly coded feature. If it's a poorly coded feature, prove it. Give an objective reason instead of calling me a "fucking cunt" or whatever it was you wrote.

Because if you tell me what's wrong with it, I can fix it and send in another pull request. If you don't want to pull it because of your own subjective bias, tell me that and don't insult my code.

**Comment by HandsomeMatt** [comment]
I really don't care. It's not getting merged in, and I think I know a fair share more about Lua than you do so please don't insult me by saying you've "bested" me.

It's not a feature PointShop needs, wants or requires, the way you implemented it was incredibly poor through the usage of timers that weren't being cleaned up properly, the general poor syntax of it all and the incredibly poor indentation. There's no configurable option for users that don't fit any of the usergroups, that's a hard coded value inside the function, it doesn't account for other admin mods that don't even use usergroups but flag permission based systems, in fact due to the massive variety in different ways servers set their users to VIP statuses this is hardly relevant at all for over half the average users of PointShop.

If you want to share this feature, release it as a separate addon, please don't continue to post here.

**Comment by PatPeter** [comment]
Finally. Thank you very much for giving me real feedback. How can I become a better Lua programmer if I am not given fair critique and assessment?

> I really don't care. It's not getting merged in, and I think I know a fair share more about Lua than you do so please don't insult me by saying you've "bested" me.

I did not mean that I bested you in terms of coding, but rather in terms of debate.

> It's not a feature PointShop needs, wants or requires, the way you implemented it was incredibly poor through the usage of timers that weren't being cleaned up properly

**I did not add a single timer in my pull request!** I merely used the timers *that were already present* in PointShop. Look:

https://github.com/PatPeter/pointshop/commit/4c47b13cd2f577309cbf8016a21162a13b213b38
https://github.com/PatPeter/pointshop/commit/80fcf45316324d033f41e676cfcd8e182160186e
https://github.com/PatPeter/pointshop/commit/dc5bc5633d7141143f60a8f5ebf87e64613b93ad

> the general poor syntax of it all

Just like your post on August 30th of last year, **please give me examples!!!** How am I supposed to fix my code and become better at Lua if you just consistently belittle my code with no evidence to back it up?

> the incredibly poor indentation

There is not a single misplaced tab in my pull request. The first and second commits contain no indentation changes. Are you talking about my for loops, which are perfectly indented?

```lua
		local potd = 10
		local pota = 1
		
		for k, v in pairs(PS.Config.PointsOverTimeDelay) do
			if self:IsUserGroup(k) then
				potd = v
				break
			end
		end
		
		for k, v in pairs(PS.Config.PointsOverTimeAmount) do
			if self:IsUserGroup(k) then
				pota = v
				break
			end
		end
```

> There's no configurable option for users that don't fit any of the usergroups, that's a hard coded value inside the function

This is a very fair point, and definitely a good reason to close the pull request. I should have retained the backwards-compatibility of modifying the default values in the config file, as well as a boolean which enables the per-usergroup time and point values, for anyone who does not want this feature enabled.

> it doesn't account for other admin mods that don't even use usergroups but flag permission based systems

An even better point! I did not know this about other admin mods, as I've only used ULX and SourceMod (the latter was a loooooong time ago lol).

> in fact due to the massive variety in different ways servers set their users to VIP statuses this is hardly relevant at all for over half the average users of PointShop.

What other ways do servers manage their VIP statuses? If I knew myself, I could work on adding broader support to my own repository, and make it even more useful for others.

**Pull request closed without merging**
